### PR TITLE
VS2013

### PR DESCRIPTION
**Pull request by SnapJag**
These are the changes for VS2013 references to SQL.DAC and a few other assemblies.

### CODE REVIEW

**Comment by SnapJag** [comment]
Thanks. A slight problem exists though. I won't delete it just yet. I compiled it fine, and then tested it on my code like I had the first set from CodePlex. It didn't work this morning. I ran the compiled code from CodePlex and it worked, but this new set doesn't work. The statement that returns is this ...

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets(1235,5): Warning:  : An exception was thrown when the ‘Smells.SML002’ rule was applied. The exception text is: ‘Object reference not set to an instance of an object.’.

I have tried to run the TEST units from , but I can't seem to get it to execute properly. I'm quite new to the Test Explorer and the tests are failing as if the SQL Unit Tests are not being processed with the DLL. The ExpectedError is being loaded from disk, but the Analyze returns but doesn't have an error, so it's not matching an error = error. So, I'm new to debugging a CodeAnalysis project so I would need to yield to you to see why this error is occurring.

If you have some good docs on how to debug a SSDT CodeAnalysis project it would be generous of you to share it with me, or something I can learn from. I'll keep trying, but I'm at that spot right now.

**Comment by SnapJag** [comment]
Sorry, one more note. I even downloaded the old CodePlex code again so I could get the original DLL to run properly like I had at the beginning to continue to run my CodeAnalysis, however, it's coming back with the same error now since working with the new code. So now I'm really stuck. Will keep trying and keep you informed, but wanted to relay the information none-the-less.

**Comment by davebally** [comment]
Hmm,  sounds like the rules are being loaded and executed,  you can debug the tests...  Try R-Click, Debug Selected Tests, it could be a bug :)
Looking at the code though, there is no exception handling in the TSQLSmellWorker.Analyze() function,  sounds like the exception can be caught there.

There is some debugging baked into ssdt that may be helpful

> Gathering an Event Log for SSDT
> 
> For diagnostic purposes we would like you to gather an event log for the issue that you are >experiencing in SSDT. In order to gather a log, please follow the steps below.
> 1. Open a new command prompt as Administrator.
> 2. Run the following command
> 
> logman create trace -n DacFxDebug -p "Microsoft-SQLServerDataTools" 0x800 -o >"%LOCALAPPDATA%\DacFxDebug.etl" -ets
> 
> logman create trace -n SSDTDebug -p "Microsoft-SQLServerDataToolsVS" 0x800 -o >"%LOCALAPPDATA%\SSDTDebug.etl" -ets
> 1. Run whatever the target/issue scenario is in SSDT.
> 2. Go back to the command prompt and run the following commands
> 
> logman stop DacFxDebug -ets
> 
> logman stop SSDTDebug -ets
> 1. The resulting ETL files will be located at %LOCALAPPDATA%\SSDTDebug.etl & >%LOCALAPPDATA%\DacFxDebug.etl and can be navigated to using Windows Explorer.
> 2. Please attach this file when creating the connect bug
> 
> NOTE - These logs will only be used by Microsoft product team members in order to better >diagnose the problem you are experiencing with SSDT and will not be shared elsewhere. If you >want to make sure that there is no private information in your ETL file, the SSDTDebug.etl file can >be opened and analyzed using the Windows Event Viewer.
> 
> To do this, open the Windows Event Viewer application. In the right-hand panel, select Open Saved >Log. Navigate to the location where you saved the log, open, and review the contents of the trace.

**Comment by SnapJag** [comment]
Thanks. I have already performed the R-Click and debugged into the SM002; however when getting to the line CodeAnalysisResult result = service.Analyze(_Model); it doesn't actually step-into (F11) this code. Sorry if this is a basic question, but how do I attach the project (which contains the .Analyze method in it) so I can step-into the .Analyze and walk through the DoSmells code? In short, I'm not doing something correct to attach the project for debugging to allow the Step-Into to get into the TSQLSmellsCA code from the TSQLSmellsSSDTTest project methods? I will look at the logs too. Thanks for the details.

**Comment by SnapJag** [comment]
Just as I pressed submit on my comment, it came to me that I needed to set the TSQLSmellSCA project as a reference to the Test project. =) If you have other information that helps me to know why the result is coming back empty, I'm open, but I am over the hump for now to debug into the .Analyze project. Thanks.

**Comment by davebally** [comment]
From this distance hard to say,  it _could_ be that the test .sql files are not being loaded due to the relative path (or something else ?!?) being different...

Check  AddFilesToModel , but that is a guess.

**Pull request merged**
